# Cho dữ liệu chronic_kidney_disease.csv chứa thông tin của các bệnh nhân. 
## Bộ dữ liệu này có thể được sử dụng để dự đoán bệnh thận mãn tính và nó được thu thập trong bệnh viện gần 2 tháng.

## Thông tin dữ liệu:
## Dữ liệu có thể tham khảo và download tại: https://archive.ics.uci.edu/ml/datasets/chronic_kidney_disease

## Data Information:
- age - age
- bp - blood pressure
- sg - specific gravity
- al - albumin
- su - sugar
- rbc - red blood cells
- pc - pus cell
- pcc - pus cell clumps
- ba - bacteria
- bgr - blood glucose random
- bu - blood urea
- sc - serum creatinine
- sod - sodium
- pot - potassium
- hemo - hemoglobin
- pcv - packed cell volume
- wc - white blood cell count
- rc - red blood cell count
- htn - hypertension
- dm - diabetes mellitus
- cad - coronary artery disease
- appet - appetite
- pe - pedal edema
- ane - anemia
- class - class

## Yêu cầu
### Đọc dữ liệu, tìm hiểu sơ bộ về dữ liệu
### Chọn phương pháp để chuẩn hóa dữ liệu và thực hiện việc chuẩn hóa.

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [19]:
col_names = ['age', 'bp', 'sg', 'al','su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class']

ckd = pd.read_csv('data5/Ex2_Chonic_Kidney_Disease_Dataset/chronic_kidney_disease.csv', header=None, names=col_names)
#header=None to command the pd.read_csv not to treat the first row as header row

ckd

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,48,80,1.02,1,0,?,normal,notpresent,notpresent,121,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7,50,1.02,4,0,?,normal,notpresent,notpresent,?,...,38,6000,?,no,no,no,good,no,no,ckd
2,62,80,1.01,2,3,normal,normal,notpresent,notpresent,423,...,31,7500,?,no,yes,no,poor,no,yes,ckd
3,48,70,1.01,4,0,normal,abnormal,present,notpresent,117,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51,80,1.01,2,0,normal,normal,notpresent,notpresent,106,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55,80,1.02,0,0,normal,normal,notpresent,notpresent,140,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42,70,1.03,0,0,normal,normal,notpresent,notpresent,75,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12,80,1.02,0,0,normal,normal,notpresent,notpresent,100,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17,60,1.03,0,0,normal,normal,notpresent,notpresent,114,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58,80,1.03,0,0,normal,normal,notpresent,notpresent,131,...,53,6800,6.1,no,no,no,good,no,no,notckd

## Predict a patient is CKD or NotCKD ("class" column") from other information
## Output: "class" column
## Input: other columns

In [22]:
ckd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     400 non-null    object
 1   bp      400 non-null    object
 2   sg      400 non-null    object
 3   al      400 non-null    object
 4   su      400 non-null    object
 5   rbc     400 non-null    object
 6   pc      400 non-null    object
 7   pcc     400 non-null    object
 8   ba      400 non-null    object
 9   bgr     400 non-null    object
 10  bu      400 non-null    object
 11  sc      400 non-null    object
 12  sod     400 non-null    object
 13  pot     400 non-null    object
 14  hemo    400 non-null    object
 15  pcv     400 non-null    object
 16  wc      400 non-null    object
 17  rc      400 non-null    object
 18  htn     400 non-null    object
 19  dm      400 non-null    object
 20  cad     400 non-null    object
 21  appet   400 non-null    object
 22  pe      400 non-null    object
 23  ane     400 non-null    object
 24  class   400 non-null    object
dtypes: object(25)
memory usage: 78.3+ KB

In [30]:
for col in col_names:
    print(f"{col} _______ {len(ckd[col].unique())} unique values: {ckd[col].unique()}")
    print()

age _______ 77 unique values: ['48' '7' '62' '51' '60' '68' '24' '52' '53' '50' '63' '40' '47' '61' '21'
 '42' '75' '69' '?' '73' '70' '65' '76' '72' '82' '46' '45' '35' '54' '11'
 '59' '67' '15' '55' '44' '26' '64' '56' '5' '74' '38' '58' '71' '34' '17'
 '12' '43' '41' '57' '8' '39' '66' '81' '14' '27' '83' '30' '4' '3' '6'
 '32' '80' '49' '90' '78' '19' '2' '33' '36' '37' '23' '25' '20' '29' '28'
 '22' '79']

bp _______ 11 unique values: ['80' '50' '70' '90' '?' '100' '60' '110' '140' '180' '120']

sg _______ 4 unique values: ['1.02' '1.01' '?' '1.03']

al _______ 7 unique values: ['1' '4' '2' '3' '0' '?' '5']

su _______ 7 unique values: ['0' '3' '4' '1' '?' '2' '5']

rbc _______ 3 unique values: ['?' 'normal' 'abnormal']

pc _______ 3 unique values: ['normal' 'abnormal' '?']

pcc _______ 3 unique values: ['notpresent' 'present' '?']

ba _______ 3 unique values: ['notpresent' 'present' '?']

bgr _______ 147 unique values: ['121' '?' '423' '117' '106' '74' '100' '410' '138' '70' '490' '380' '208'
 '98' '157' '76' '99' '114' '263' '173' '95' '108' '156' '264' '123' '93'
 '107' '159' '140' '171' '270' '92' '137' '204' '79' '207' '124' '144'
 '91' '162' '246' '253' '141' '182' '86' '150' '146' '425' '112' '250'
 '360' '163' '129' '133' '102' '158' '165' '132' '104' '127' '415' '169'
 '251' '109' '280' '210' '219' '295' '94' '172' '101' '298' '153' '88'
 '226' '143' '115' '89' '297' '233' '294' '323' '125' '90' '308' '118'
 '224' '128' '122' '214' '213' '268' '256' '84' '105' '288' '139' '78'
 '273' '242' '424' '303' '148' '160' '192' '307' '220' '447' '309' '22'
 '111' '261' '215' '234' '131' '352' '80' '239' '110' '130' '184' '252'
 '113' '230' '341' '255' '103' '238' '248' '120' '241' '269' '201' '203'
 '463' '176' '82' '119' '97' '96' '81' '116' '134' '85' '83' '87' '75']

bu _______ 118 unique values: ['36' '18' '53' '56' '26' '25' '54' '31' '60' '107' '55' '72' '86' '90'
 '162' '46' '87' '27' '148' '180' '163' '?' '50' '75' '45' '28' '155' '33'
 '39' '153' '29' '65' '103' '70' '80' '20' '202' '77' '89' '24' '17' '32'
 '114' '66' '38' '164' '142' '96' '391' '15' '111' '73' '19' '92' '35'
 '16' '139' '48' '85' '98' '186' '37' '47' '52' '82' '51' '106' '22' '217'
 '88' '118' '71' '34' '40' '21' '219' '30' '125' '166' '49' '208' '176'
 '68' '145' '165' '322' '23' '235' '132' '76' '42' '44' '41' '113' '2'
 '146' '58' '133' '137' '67' '115' '223' '99' '158' '94' '74' '150' '61'
 '57' '95' '191' '93' '241' '64' '79' '215' '309' '10']

sc _______ 85 unique values: ['1.2' '0.8' '1.8' '3.8' '1.4' '1.1' '24' '1.9' '7.2' '4' '2.7' '2.1'
 '4.6' '4.1' '9.6' '2.2' '5.2' '1.3' '1.6' '3.9' '76' '7.7' '?' '2.4'
 '7.3' '1.5' '2.5' '2' '3.4' '0.7' '1' '10.8' '6.3' '5.9' '0.9' '3' '3.25'
 '9.7' '6.4' '3.2' '32' '0.6' '6.1' '3.3' '6.7' '8.5' '2.8' '15' '2.9'
 '1.7' '3.6' '5.6' '6.5' '4.4' '10.2' '11.5' '0.5' '12.2' '5.3' '9.2'
 '13.8' '16.9' '6' '7.1' '18' '2.3' '13' '48.1' '14.2' '16.4' '2.6' '7.5'
 '4.3' '18.1' '11.8' '9.3' '6.8' '13.5' '12.8' '11.9' '12' '13.4' '15.2'
 '13.3' '0.4']

sod _______ 35 unique values: ['?' '111' '142' '104' '114' '131' '138' '135' '130' '141' '139' '5' '136'
 '129' '140' '132' '133' '134' '125' '163' '137' '128' '143' '127' '146'
 '126' '122' '147' '124' '115' '145' '113' '120' '150' '144']

pot _______ 41 unique values: ['?' '2.5' '3.2' '4' '3.7' '4.2' '5.8' '3.4' '6.4' '4.9' '4.1' '4.3' '5.2'
 '3.8' '4.6' '3.9' '4.7' '5.9' '4.8' '4.4' '6.6' '39' '5.5' '5' '3.5'
 '3.6' '7.6' '2.9' '4.5' '5.7' '5.4' '5.3' '47' '6.3' '5.1' '5.6' '3'
 '2.8' '2.7' '6.5' '3.3']

hemo _______ 116 unique values: ['15.4' '11.3' '9.6' '11.2' '11.6' '12.2' '12.4' '10.8' '9.5' '9.4' '9.7'
 '9.8' '5.6' '7.6' '12.6' '12.1' '12.7' '10.3' '7.7' '10.9' '?' '11.1'
 '9.9' '12.5' '12.9' '10.1' '12' '13' '7.9' '9.3' '15' '10' '8.6' '13.6'
 '10.2' '10.5' '6.6' '11' '7.5' '15.6' '15.2' '4.8' '9.1' '8.1' '11.9'
 '13.5' '8.3' '7.1' '16.1' '10.4' '9.2' '6.2' '13.9' '14.1' '6' '11.8'
 '11.7' '11.4' '14' '8.2' '13.2' '6.1' '8' '12.3' '8.4' '14.3' '9' '8.7'
 '10.6' '13.1' '10.7' '5.5' '5.8' '6.8' '8.8' '8.5' '13.8' '11.5' '7.3'
 '13.7' '12.8' '13.4' '6.3' '3.1' '17' '15.9' '14.5' '15.5' '16.2' '14.4'
 '14.2' '16.3' '14.8' '16.5' '15.7' '13.3' '14.6' '16.4' '16.9' '16'
 '14.7' '16.6' '14.9' '16.7' '16.8' '15.8' '15.1' '17.1' '17.2' '15.3'
 '17.3' '17.4' '17.7' '17.8' '17.5' '17.6']

pcv _______ 43 unique values: ['44' '38' '31' '32' '35' '39' '36' '33' '29' '28' '?' '16' '24' '37' '30'
 '34' '40' '45' '27' '48' '52' '14' '22' '18' '42' '17' '46' '23' '19'
 '25' '41' '26' '15' '21' '43' '20' '47' '9' '49' '50' '53' '51' '54']

wc _______ 90 unique values: ['7800' '6000' '7500' '6700' '7300' '?' '6900' '9600' '12100' '4500'
 '12200' '11000' '3800' '11400' '5300' '9200' '6200' '8300' '8400' '10300'
 '9800' '9100' '7900' '6400' '8600' '18900' '21600' '4300' '8500' '11300'
 '7200' '7700' '14600' '6300' '7100' '11800' '9400' '5500' '5800' '13200'
 '12500' '5600' '7000' '11900' '10400' '10700' '12700' '6800' '6500'
 '13600' '10200' '9000' '14900' '8200' '15200' '5000' '16300' '12400'
 '10500' '4200' '4700' '10900' '8100' '9500' '2200' '12800' '11200'
 '19100' '12300' '16700' '2600' '26400' '8800' '7400' '4900' '8000'
 '12000' '15700' '4100' '5700' '11500' '5400' '10800' '9900' '5200' '5900'
 '9300' '9700' '5100' '6600']

rc _______ 46 unique values: ['5.2' '?' '3.9' '4.6' '4.4' '5' '4' '3.7' '3.8' '3.4' '2.6' '2.8' '4.3'
 '3.2' '3.6' '4.1' '4.9' '2.5' '4.2' '4.5' '3.1' '4.7' '3.5' '6' '2.1'
 '5.6' '2.3' '2.9' '2.7' '8' '3.3' '3' '2.4' '4.8' '5.4' '6.1' '6.2' '6.3'
 '5.1' '5.8' '5.5' '5.3' '6.4' '5.7' '5.9' '6.5']

htn _______ 3 unique values: ['yes' 'no' '?']

dm _______ 4 unique values: ['yes' 'no' ' yes' '?']

cad _______ 3 unique values: ['no' 'yes' '?']

appet _______ 3 unique values: ['good' 'poor' '?']

pe _______ 3 unique values: ['no' 'yes' '?']

ane _______ 3 unique values: ['no' 'yes' '?']

class _______ 2 unique values: ['ckd' 'notckd']

## There many columns have "?" value, therefore their type is "object" => Replace "?" with np.nan
## Also, numeric data is written within '...', which makes them become a string => Use pd.numeric(..., errors='coerce')

In [72]:
ckd_clean = ckd.replace('?', np.nan)

col_numeric = ['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc']

for col in col_numeric:
    ckd_clean[col] = pd.to_numeric(ckd_clean[col])

ckd_clean

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.02,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.02,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.01,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.01,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.01,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.02,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.03,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.02,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.03,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.03,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [74]:
ckd_clean.isnull().sum()

age        9
bp        12
sg        47
al        46
su        49
rbc      152
pc        65
pcc        4
ba         4
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      52
pcv       71
wc       106
rc       131
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
class      0
dtype: int64

## There are many rows with NaN values
## For numeric columns => replace NaN with median
## For categorical columns => drop

## Preprocess the numeric columns first, then dropna in categorical ones to reduce the number of deleted rows

In [77]:
for col in col_numeric:
    ckd_clean[col] = ckd_clean[col].fillna(ckd_clean[col].median())

ckd_no_na = ckd_clean.dropna()
ckd_no_na

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
2,62.0,80.0,1.01,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,4.8,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.01,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.01,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
7,24.0,80.0,1.02,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,...,44.0,6900.0,5.0,no,yes,no,good,yes,no,ckd
8,52.0,100.0,1.02,3.0,0.0,normal,abnormal,present,notpresent,138.0,...,33.0,9600.0,4.0,yes,yes,no,good,no,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.02,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.03,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.02,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.03,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.03,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [81]:
ckd_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Index: 233 entries, 2 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     233 non-null    float64
 1   bp      233 non-null    float64
 2   sg      233 non-null    float64
 3   al      233 non-null    float64
 4   su      233 non-null    float64
 5   rbc     233 non-null    object
 6   pc      233 non-null    object
 7   pcc     233 non-null    object
 8   ba      233 non-null    object
 9   bgr     233 non-null    float64
 10  bu      233 non-null    float64
 11  sc      233 non-null    float64
 12  sod     233 non-null    float64
 13  pot     233 non-null    float64
 14  hemo    233 non-null    float64
 15  pcv     233 non-null    float64
 16  wc      233 non-null    float64
 17  rc      233 non-null    float64
 18  htn     233 non-null    object
 19  dm      233 non-null    object
 20  cad     233 non-null    object
 21  appet   233 non-null    object
 22  pe      233 non-null    object
 23  ane     233 non-null    object
 24  class   233 non-null    object
dtypes: float64(14), object(11)
memory usage: 47.3+ KB

## In ckd_no_na, there are categorical columns whose dtypes==object
## => Set a boolean conditon (mask) to filter out these categorical columns

In [88]:
categorical_mask = ckd_no_na.dtypes=="object" #Set boolean conditon
 
col_categorical = ckd_no_na.columns[categorical_mask] #get categorical "object" columns using boolean condition

col_categorical

Index(['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane',
       'class'],
      dtype='object')

## Problem: the two ouput values "ckd" and "notckd" are not so balanced in quantities
## Keep using Logistic Regression model, if the result is not as good as expected, then apply Data Balancing method

In [100]:
ckd_no_na['class'].value_counts()

class
notckd    135
ckd        98
Name: count, dtype: int64

## Since the output have only <span style='color:red;'>two values (binary values)</span> = 'ckd' or 'notckd'
## Can build <span style='color:red;'>Logistic Regression model</span> to predict

## Also, we <span style='color:yellow;'>only need to encode CATEGORICAL features/columns</span>, while numeric ones do not

In [149]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#from sklearn.utils.validation import column_or_1d

x = ckd_no_na.drop(['class'], axis=1)
x = pd.get_dummies(x, columns=col_categorical[:-1], drop_first=True).astype(int) #use dummies method to encode categorical columns
                                                                                #set col_categorical[:-1] to exclude the 'class' column

y = pd.get_dummies(ckd_no_na[['class']],).drop('class_notckd', axis=1).astype(int)
#encode y 'class' with dummies too

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [151]:
model_log_reg = LogisticRegression(solver='liblinear')

'''
solver='liblinear': This specifies the algorithm used to fit the logistic regression model. 
The 'liblinear' solver is one of the solvers available in Scikit-learn, which is particularly efficient for smaller datasets 
or when you need an implementation that works well for binary classification. It uses coordinate descent or a trust region method to optimize the model.
'''

model_log_reg.fit(x_train, y_train)

print("Log_reg model's score on Train set =", model_log_reg.score(x_train, y_train))
print("Log_reg model's score on Test set =", model_log_reg.score(x_test, y_test))

Log_reg model's score on Train set = 1.0
Log_reg model's score on Test set = 0.9574468085106383

/home/long/Documents/DataScience_hcmus/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [153]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred_test = model_log_reg.predict(x_test)

print(confusion_matrix(y_test, y_pred_test))

print()

print(classification_report(y_test, y_pred_test))

[[26  0]
 [ 2 19]]

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        26
           1       1.00      0.90      0.95        21

    accuracy                           0.96        47
   macro avg       0.96      0.95      0.96        47
weighted avg       0.96      0.96      0.96        47

## <span style='color:red'>Results:
### + The model has good results on both train and test set
### + Confusion matrix also reports high results