# Chap 13 - Ex3: apply Apriori for dataset_group.csv

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

np.set_printoptions(suppress = True)
pd.set_option('display.width', 1000)

In [22]:
dataset_group = (
    pd.read_csv('Data/dataset_group.csv', header=None)
    .set_axis(['Date', 'Order', 'Items'], axis = 1) #set columns' names
)

dataset_group

             Date  Order              Items
0      2000-01-01      1             yogurt
1      2000-01-01      1               pork
2      2000-01-01      1      sandwich bags
3      2000-01-01      1         lunch meat
4      2000-01-01      1       all- purpose
...           ...    ...                ...
22338  2002-02-26   1139               soda
22339  2002-02-26   1139  laundry detergent
22340  2002-02-26   1139         vegetables
22341  2002-02-26   1139            shampoo
22342  2002-02-26   1139         vegetables

[22343 rows x 3 columns]

## <span style = 'color : yellow'> Convert dataframe into list of transactions

In [54]:
dataset_group_condensed = dataset_group.groupby('Order')['Items'].agg(lambda x: list(x))

print(dataset_group_condensed)

transactions_lst = dataset_group_condensed.tolist()

Order
1       [yogurt, pork, sandwich bags, lunch meat, all-...
2       [toilet paper, shampoo, hand soap, waffles, ve...
3       [soda, pork, soap, ice cream, toilet paper, di...
4       [cereals, juice, lunch meat, soda, toilet pape...
5       [sandwich loaves, pasta, tortillas, mixes, han...
                              ...
1135    [sugar, beef, sandwich bags, hand soap, paper ...
1136    [coffee/tea, dinner rolls, lunch meat, spaghet...
1137    [beef, lunch meat, eggs, poultry, vegetables, ...
1138    [sandwich bags, ketchup, milk, poultry, cheese...
1139    [soda, laundry detergent, vegetables, shampoo,...
Name: Items, Length: 1139, dtype: object

## <span style = 'color : yellow'> Use TransactionEncoder to handle transactions_lst

In [59]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

trans_encode = TransactionEncoder()
trans_encode.fit(transactions_lst)

arr_transactions = trans_encode.transform(transactions_lst)

df_transactions = pd.DataFrame(arr_transactions, columns = trans_encode.columns_)
df_transactions

      all- purpose  aluminum foil  bagels   beef  butter  cereals  cheeses  coffee/tea  dinner rolls  dishwashing liquid/detergent  ...  shampoo   soap   soda  spaghetti sauce  sugar  toilet paper  tortillas  vegetables  waffles  yogurt
0             True           True   False   True    True    False    False       False          True                         False  ...     True   True   True            False  False         False      False        True    False    True
1            False           True   False  False   False     True     True       False         False                          True  ...     True  False  False            False  False          True       True        True     True    True
2            False          False    True  False   False     True     True       False          True                         False  ...     True   True   True             True  False          True      False        True    False   False
3             True          False   False  False   False     True    False       False         False                         False  ...    False  False   True            False  False          True      False       False    False   False
4             True          False   False  False   False    False    False       False          True                         False  ...    False  False   True             True  False          True       True        True     True    True
...            ...            ...     ...    ...     ...      ...      ...         ...           ...                           ...  ...      ...    ...    ...              ...    ...           ...        ...         ...      ...     ...
1134          True          False   False   True   False     True     True        True          True                          True  ...     True   True  False            False   True         False      False       False    False   False
1135         False          False   False  False   False     True     True        True          True                          True  ...    False   True  False             True  False         False      False        True    False   False
1136         False          False    True   True   False    False    False       False          True                          True  ...     True   True  False            False   True         False       True        True    False    True
1137          True          False   False   True   False    False     True       False         False                         False  ...    False   True   True             True   True          True      False        True     True    True
1138         False          False   False  False   False    False    False       False         False                         False  ...     True  False   True            False  False         False      False        True    False   False

[1139 rows x 38 columns]

## <span style = 'color : yellow'> Apply apriori and association_rules

In [70]:
frequent_items = apriori(df_transactions, min_support=0.3, use_colnames=True)
frequent_items

     support                                    itemsets
0   0.374890                              (all- purpose)
1   0.384548                             (aluminum foil)
2   0.385426                                    (bagels)
3   0.374890                                      (beef)
4   0.367867                                    (butter)
5   0.395961                                   (cereals)
6   0.390694                                   (cheeses)
7   0.379280                                (coffee/tea)
8   0.388938                              (dinner rolls)
9   0.388060              (dishwashing liquid/detergent)
10  0.389816                                      (eggs)
11  0.352941                                     (flour)
12  0.370500                                    (fruits)
13  0.345917                                 (hand soap)
14  0.398595                                 (ice cream)
15  0.375768                          (individual meals)
16  0.376646                                     (juice)
17  0.371378                                   (ketchup)
18  0.378402                         (laundry detergent)
19  0.395083                                (lunch meat)
20  0.380158                                      (milk)
21  0.375768                                     (mixes)
22  0.362599                              (paper towels)
23  0.371378                                     (pasta)
24  0.355575                                      (pork)
25  0.421422                                   (poultry)
26  0.367867                             (sandwich bags)
27  0.349429                           (sandwich loaves)
28  0.368745                                   (shampoo)
29  0.379280                                      (soap)
30  0.390694                                      (soda)
31  0.373134                           (spaghetti sauce)
32  0.360843                                     (sugar)
33  0.378402                              (toilet paper)
34  0.369622                                 (tortillas)
35  0.739245                                (vegetables)
36  0.394205                                   (waffles)
37  0.384548                                    (yogurt)
38  0.310799                 (vegetables, aluminum foil)
39  0.300263                        (bagels, vegetables)
40  0.310799                       (cereals, vegetables)
41  0.309043                       (cheeses, vegetables)
42  0.308165                  (dinner rolls, vegetables)
43  0.306409  (vegetables, dishwashing liquid/detergent)
44  0.326602                          (eggs, vegetables)
45  0.302897                     (ice cream, vegetables)
46  0.309043             (laundry detergent, vegetables)
47  0.311677                    (lunch meat, vegetables)
48  0.331870                       (poultry, vegetables)
49  0.305531                          (soda, vegetables)
50  0.315189                       (vegetables, waffles)
51  0.319579                        (vegetables, yogurt)

In [75]:
asc_rules = association_rules(frequent_items, metric='lift', min_threshold=1.1,
                             return_metrics=['support', 'confidence', 'lift', 'leverage', 'conviction'])
asc_rules

           antecedents          consequents   support  confidence      lift  leverage  conviction
0               (eggs)         (vegetables)  0.326602    0.837838  1.133370  0.038433    1.607989
1         (vegetables)               (eggs)  0.326602    0.441805  1.133370  0.038433    1.093139
2  (laundry detergent)         (vegetables)  0.309043    0.816705  1.104783  0.029311    1.422600
3         (vegetables)  (laundry detergent)  0.309043    0.418052  1.104783  0.029311    1.068134
4         (vegetables)             (yogurt)  0.319579    0.432304  1.124188  0.035304    1.084123
5             (yogurt)         (vegetables)  0.319579    0.831050  1.124188  0.035304    1.543388